### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by JakeHenshall** [ducdev/aliexscrape#7]
Hey,

I run this code scrape 32853590425

But I get this error:

TypeError: Cannot read property '1' of null
    at /Users/jake/Code/aliexscrape/index.js:12:65
    at tryCatcher (/Users/jake/Code/aliexscrape/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jake/Code/aliexscrape/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jake/Code/aliexscrape/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jake/Code/aliexscrape/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jake/Code/aliexscrape/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/jake/Code/aliexscrape/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/jake/Code/aliexscrape/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/jake/Code/aliexscrape/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jake/Code/aliexscrape/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
undefined

Thanks Jake.

**Comment by molotow11** [comment]
I have the same issue

**Comment by DestroyerIV** [comment]
the same problem...

**Comment by mezzab** [comment]
Same problem!

**Comment by ducdev** [comment]
Sorry guys for late response, actually I don't have much time for aliexscrape, then feel free to submit your PR and I will consider merging, thanks.

**Comment by aorfevre** [comment]
sounds like it request an authentication from cheerio; prompting the auth screen from aliexpress before showing the result.
Don't know how to do authenticate cheerio to aliexpress
if you can put me to the direction @ducdev ; I would love to invest time for that.

**Comment by ducdev** [comment]
> sounds like it request an authentication from cheerio; prompting the auth screen from aliexpress before showing the result.
> Don't know how to do authenticate cheerio to aliexpress
> if you can put me to the direction @ducdev ; I would love to invest time for that.

If you are keen on and having time for it, please work around and submit your PR, thanks.

**Comment by fremeni** [comment]
Hi guys, I have some money to invest to make this great base even better. Anyone avaiable to work on this? Contact me at account@pricefy.io
